export enum AuthMutations {
    FETCH_TOKEN = 'SET_TOKEN',
    SET_EMAIL = 'SET_EMAIL'
}

export enum UserMutations {
    FETCH_INFORMATION = "FETCH_INFORMATION"
}

export enum AnalyticMutations {
    FETCH_DAILY_SALES_OVERVIEW = "FETCH_DAILY_SALES_OVERVIEW",
    FETCH_DAILY_SALES_SKU_LIST = "FETCH_DAILY_SALES_SKU_LIST",
    FETCH_GET_SKU_REFUND_RATE = "FETCH_GET_SKU_REFUND_RATE"
}